apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "app.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{  .Values.nfs.storageClassName }}
  resources:
    requests:
      storage: 1Gi