apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.nfs.storageClassName }}
provisioner: nfs.csi.k8s.io
parameters:
  server: {{ $.Values.nfs.server }}
  share:  {{ $.Values.nfs.path }}
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1