architecture: replication
auth:
  enabled: true

replica:
  replicaCount: 3

persistence:
  enabled: false
  size: 8Gi

resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "256Mi"
    cpu: "100m"

service:
  type: ClusterIP
  ports:
    redis: 6379

master:
  disableCommands: []
  persistence:
    enabled: false

usePassword: true
cluster:
  enabled: true
  slaveCount: 2 

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 1

livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 5

sentinel:
  enabled: false

metrics:
  enabled: false

volumePermissions:
  enabled: true